### ISSUE TITLE
Fix custom font loading in IE for SVG placeholders, if possible

### ISSUE THREAD

**Issue by imsky** [imsky/holder#160]

**Comment by usamamuneeb** [comment]
I noticed this issue back in [August 2015](http://stackoverflow.com/questions/32285832/custom-font-on-holder-js-objects). Since no description is provided, I'll provide it here.

If we want to use custom fonts, we are forced to use <object> placeholders instead of <img>. Custom fonts do not load with <img>. I've uploaded an example at [this URL](https://lumun.lums.edu.pk/imsky/issue.htm). If viewed in Firefox, Opera or Chrome, you'll see two boxes. The one on the left uses <object> and the one on the right uses <img>. Custom font is only seen correctly in the one on the left.

The drawback of <object> is that it doesn't work in IE and Edge, which is another bug. Heck, if you view the same URL I linked above in IE, you will see only one box, the one that uses <img>. Either <object> should work in IE and Edge seamlessly or <img> should support custom fonts.

I believe both issues should be fixed since the only advantage of using <object> is when you want to inspect the DOM with JavaScript or JQuery. <object> should definitely work in IE and Edge and <img> should support custom fonts, since if one wants to export a save-able image to the browser using holder, they are able to do so.

**Comment by imsky** [comment]
IMG won't support custom fonts - there's a cross-origin issue with SVGs. i'll confirm to see if anything's changed in the last few months.

as far as the topic, this is only relevant to SVG placeholders. canvas placeholders should work fine.
