### ISSUE TITLE
Trying to get full width

### ISSUE THREAD

**Issue by riwakawebsitedesigns** [imsky/holder#190]
I am using the latest version of holder.js but I am un able to use the percentage `%` to get full width of div? How can I get it to pic up full width of div?

```
<div class="head-content">
<div class="col-lg-12">
<img src="holder.js/100%x380">
</div>
</div>
```

**Comment by imsky** [comment]
try `holder.js/100px380`

**Comment by riwakawebsitedesigns** [comment]
That worked

**Comment by imsky** [comment]
excellent, glad to help 😄

**Comment by SAPHemlock** [comment]
Thanks. Its working and now the holderjs image is responsive.
Can you please explain a littlebit how it worked or just general idea of the fix?

**Comment by imsky** [comment]
@SAPHemlock the "p" is what makes the holder responsive, because "%" has a special meaning in URLs

so `holder.js/100px380` means "create a placeholder 100% wide and 380 pixels tall"

this is processed with the fluid flag here https://github.com/imsky/holder/blob/178166049c8ff03847b687a99d533e8efa92f08d/holder.js#L622

and set in the DOM here https://github.com/imsky/holder/blob/178166049c8ff03847b687a99d533e8efa92f08d/holder.js#L845
